ecommerce_project/cartapp/urls.py
from django.urls import path
from . import views

app_name='cartapp'
urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('cart_full_remove/<int:product_id>/',views.cart_full_remove,name='cart_full_remove')

]

ecommerce_project/ecommerce_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('storeapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cartapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce_project/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns=[
    path('',views.searchresult,name='searchresult'),
]

ecommerce_project/storeapp/urls.py
from . import views
from django.urls import path, include
app_name = 'storeapp'
urlpatterns = [

    path('',views.allprodca,name='allprodca'),
    path('<slug:c_slug>/',views.allprodca,name='products_by_Category'),
    path('<slug:c_slug>/<slug:product_slug>',views.proddetail,name='prodcadetail')
]

ecommerce_project/cartapp/models.py
from django.db import models
from storeapp.models import Product
# Create your models here.


class Cart(models.Model):

    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce_project/search_app/models.py
from django.db import models

# Create your models here.

ecommerce_project/storeapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    discription = models.TextField(blank=True)
    image = models.ImageField(upload_to='category_image',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('storeapp:products_by_Category', args=[self.slug])




    def __str__(self):
        return self.name


class Product(models.Model):

    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    price = models.DecimalField(default=0, decimal_places=2,max_digits=10)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='product_image')
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('storeapp:prodcadetail', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

ecommerce_project/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from storeapp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.
def cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()

    return cart


def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=cart_id(request))
        cart.save(),

    try:
        cart_item = CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()

    except CartItem.DoesNotExist:

        cart_item = CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()
    return redirect('cartapp:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)  # Access quantity for each cart_item
            counter += cart_item.quantity  # Access quantity for each cart_item

    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request,product_id):
    cart= Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()

    return redirect('cartapp:cart_detail')

def cart_full_remove(request,product_id):
    cart= Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cartapp:cart_detail')

ecommerce_project/search_app/views.py
from django.shortcuts import render
from storeapp.models import Product
from django.db.models import Q

# Create your views here.

def searchresult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query)|Q(description__contains=query))
        return render(request,'search.html',{'query':query,'products':products})

ecommerce_project/storeapp/views.py
from django.shortcuts import render,get_object_or_404
from . models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.
# def home(request):
#     return render(request,'base.html')

def allprodca(request,c_slug=None):
    c_page = None
    products_list = None
    if c_slug!=None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
        page=int(request.GET.get('page',1))
    except:
        page=1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)


    return render(request,'category.html',{'category':c_page,'products':products})

def proddetail(request, c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e

    return render(request,'product.html',{'product':product})

ecommerce_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/0a3259cc1e.js" crossorigin="anonymous"></script>
    <meta name="discription" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>

  </head>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

</div>

</body>
</html>

ecommerce_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
       This is the cart page, proceed to review the items and  place the order


{% endblock %}
{% block title %}
    Cart ShopSwift Pvt LTD

{% endblock %}
{% block content %}
<div class="content-wrapper">
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your Shopping Cart is empty</h1>
        <br>
        <p class="text-center">
            Please click <a href="{% url 'storeapp:allprodca' %}">Here</a>to continue shopping
        </p>

    </div>
</div>
{% else %}
<div>
    <div>
        <br>
        <h1 class="text-center my_title">Your Shopping Cart</h1>
        <br>
    </div>
    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                        Your Item

                    </th>
                </tr>

                </thead>
                <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="{{ cart_item.product.get_absolute_url }}"><img src="{{ cart_item.product.image.url }}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a>

                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU: {{cart_item.product.id}}
                        <br>
                        Price : ${{cart_item.product.price}}
                        <br>
                        Quantity: {{cart_item.quantity}} X {{cart_item}}
                    </td>
                    <td>
                        $ {{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cartapp:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-plus custom_icon"></i></a>&nbsp;
                        <a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-minus custom_icon"></i></a>&nbsp;
                        <a href="{% url 'cartapp:cart_full_remove' cart_item.product.id %}" class="custom_icon"> <i class="fa-solid fa-trash custom_icon"> </i></a>
                    </td>
                    {% else %}
                    <td>
                        &nbsp;<a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-minus custom_icon"> </i></a>
                        &nbsp;<a href="{% url 'cartapp:cart_full_remove' cart_item.product.id %}" class="custom_icon"> <i class="fa-solid fa-trash custom_icon"> </i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        Please take a moment to review the items in your shopping cart before finalizing your order payment.
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        Your Total is : <strong>{{ total }}</strong>
                    </td>
                </tr>

                </tbody>
            </table>
            <div class="mx-auto">
    <div class="row">
        <div class="col-md-6">
            <a href="{% url 'storeapp:allprodca' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
        </div>
        <div class="col-md-6">
            <a href="{% url 'storeapp:allprodca' %}" class="btn btn-secondary btn-block my_custom_button">Proceed to Payment</a>
        </div>
    </div>
</div>


{% endif %}
        </div>
    </div>
</div>
</div>
{% endblock %}

ecommerce_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to ShopSwift where you can shop in style
    {% endif %}
{% endblock %}
{% block title %}
{% if category %}
        {{ category.title }} -- SopSwift
    {% else %}
        Our Collections -- ShopSwift
    {% endif %}
{% endblock %}
{% block content %}
{% if category %}
    <div>
        <div class="row my-row-class">
            <div class="mx-auto">
            <p> <a href="{% url 'storeapp:allprodca' %}"> Our Products</a></p>
            </div>
        </div>
    </div>
{% endif %}
<div class="mx-auto">
    {% if category %}
        <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div>
<br>
<div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p>
</div>
    {% else %}
<div>
        <img class="my_image my_image_padding" src="{% static 'image/banner.png' %}" alt="our products">
    </div>
<br>
<div>
        <h1 class="text-center my_title">Our Collections</h1>
        <p class="text-justify">Discover a World of Technology at Your Fingertips! Explore our curated collections of laptops, phones, and more, designed to elevate your digital lifestyle. Shop now for the latest in innovation and convenience.</p>
</div>
    {% endif %}
<div class="container">
    <div class="row mx-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto pagination-container">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

ecommerce_project/templates/footer.html
<!--<div class="footer navbar-fixed-bottom my_footer">-->
<!--    <p class="text-center">&copy; ShopSwift pvt ltd. All right Reserved</p>-->
<!--</div>-->

<div class="footer my_footer">
    <p class="text-center">&copy; ShopSwift pvt ltd. All right Reserved</p>
</div>

ecommerce_project/templates/header.html
{% load static %}
<header>
    <center>
       <a href="{% url 'storeapp:allprodca' %}"> <img src="{% static 'image/shoplogo.png' %}" alt="logo" width="130px" height="130px"></a>

    </center>
</header> 

ecommerce_project/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'storeapp:allprodca' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Shop</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Products
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'storeapp:allprodca' %}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cartapp:cart_detail' %}"><i class="fa-solid fa-cart-plus"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:searchresult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce_project/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }} -- SopSwift
    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'storeapp:allprodca' %}">Home</a> | <a href="{{ product.category.get_url }}">{{product.category}}</a> | {{product.name}}</p>
    </div>

<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}">
        </div>
    </div>

        <div class="col-12 col-sm12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>{{product.price}}</p>
            <p class="my_title">product description</p>
            <p class="text-justify my_rod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out of stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cartapp:add_cart' product.id %}">Add to cart</a>
            {% endif %}
            </div>
        </div>
    </div>
    </div>
</div>

{% endblock %} <!-- Add this line to close the 'content' block -->

ecommerce_project/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        we have variety of products


{% endblock %}
{% block title %}
    Search

{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for:<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="mx-auto">
            <p class="text-center my_search_text">0 results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}